apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-aks-cicd
  namespace: default
  labels:
    app: genai-aks-cicd
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: genai-aks-cicd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: genai-aks-cicd
    spec:
      containers:
        - name: genai-aks-cicd
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
